services:

  web:
    image: app-angular
    build:
      context: ./parc
      args:
        MY_UID: ${MY_UID:-1000}
        MY_GID: ${MY_GID:-1000}
   
    command: ./init-angular.sh
    volumes:
      - ./parc:/home/node/app
    ports:
      - "4200:4200"
    restart: always

  api:
    image: app-python
    build:
      context: ./python
    volumes:
      - ./python:/var/www/html/back
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      database:
        condition: service_healthy  

  database:
    image: mariadb:latest
    volumes:
      - database_data:/var/lib/mysql  
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlroot
      - MYSQL_DATABASE=parc
      - MYSQL_USER=mysqlusr
      - MYSQL_PASSWORD=mysqlpwd
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "--password=mysqlroot"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "443:443"
    depends_on:
      - web
      - api
    restart: always

volumes:
  database_data: